name: Dispatch new changes
on:
  push:
jobs:
  release: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch new changes in library ocurred 
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/jonaslagoni/autofix-example-user/actions/workflows/dispatch.yml/dispatches --data '{"ref": "master"}'
          